version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    environment:
      - MONGODB_URI=mongodb://mongo:mongo@animavita_mongo/?authMechanism=DEFAULT
  mongodb:
    container_name: animavita_mongo
    image: mongo:6.0.2
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      - MONGO_INITDB_DATABASE=animavita
    volumes:
      - mongo:/data/db
volumes:
  mongo:
